version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./laravel-php:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public